# Generated by Django 4.2.3 on 2023-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_notes_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningnote",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
