# Generated by Django 5.1 on 2024-08-31 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_notes_app", "0002_learningnote_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningnote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Learning Note",
                "verbose_name_plural": "Learning Notes",
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(max_length=7)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="learningnote",
            name="labels",
            field=models.ManyToManyField(
                related_name="learning_notes", to="learning_notes_app.label"
            ),
        ),
        migrations.AddIndex(
            model_name="learningnote",
            index=models.Index(
                fields=["user", "created_at"], name="learning_no_user_id_c272da_idx"
            ),
        ),
    ]
